services:

  mappers:
    image: mappers
    build: ../mapper-packages
    network_mode: host
    ipc: host
    restart: unless-stopped
    tty: true
    volumes:
      - ~/map:/map
      - ~/heatmaps:/heatmaps
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0

  rviz:
    image: husarion/rviz2:humble
    network_mode: host
    ipc: host
    restart: on-failure
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./config/rosbot_pro_mapping.rviz:/root/.rviz2/default.rviz
    environment:
      - DISPLAY
      - LIBGL_ALWAYS_SOFTWARE=1
      - RMW_IMPLEMENTATION=rmw_cyclonedds_cpp
      - ROS_DOMAIN_ID=0
